#include "customcode_p4OTtGwLt8ENvzdl38NWBD.h"
#ifdef __cplusplus
extern "C" {
#endif


/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */
DLL_EXPORT_CC extern const char_T *get_dll_checksum_p4OTtGwLt8ENvzdl38NWBD(void);
DLL_EXPORT_CC extern void cblas_chpr2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *Ap);
DLL_EXPORT_CC extern real_T cblas_dnrm2_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztpsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern real32_T cblas_snrm2_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctpmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dtbsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_saxpy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cscal_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztrsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern uint64_T cblas_izamax_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zhpr2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *Ap);
DLL_EXPORT_CC extern void cblas_zhpmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *Ap, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zhemm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_cdotu_sub_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotu);
DLL_EXPORT_CC extern void cblas_sscal_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T alpha, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_cdotc_sub_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotc);
DLL_EXPORT_CC extern void cblas_cswap_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_sspmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *Ap, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dcopy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T *X, const int32_T incX, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_sgemv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zhbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ssymv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zhpr_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, void *X, const int32_T incX, void *A);
DLL_EXPORT_CC extern void cblas_zgerc_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zaxpy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zher2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zswap_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ssyrk_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void mpc_p4OTtGwLt8ENvzdl38NWBD(int32_T T, int32_T m, int32_T n, int32_T niters, real_T kappa, real_T *A, real_T *B, real_T *Q, real_T *Qf, real_T *R, real_T *xmin, real_T *xmax, real_T *umin, real_T *umax, real_T *X0, real_T *U0, real_T *x0, real_T *U, real_T *X);
DLL_EXPORT_CC extern void cblas_scopy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cher2k_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, const real32_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_strsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern uint64_T cblas_icamax_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zherk_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real_T alpha, void *A, const int32_T lda, const real_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_stpmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *Ap, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zscal_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zsyrk_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_csyr2k_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_ccopy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dsymv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_strmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dspr2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY, real_T *A);
DLL_EXPORT_CC extern void cblas_chbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern real_T cblas_dznrm2_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void fmpcsolve_p4OTtGwLt8ENvzdl38NWBD(real_T *A, real_T *B, real_T *At, real_T *Bt, real_T *eyen, real_T *eyem, real_T *Q, real_T *R, real_T *Qf, real_T *zmax, real_T *zmin, real_T *x, real_T *z, int32_T T, int32_T n, int32_T m, int32_T nz, int32_T niters, real_T kappa);
DLL_EXPORT_CC extern void cblas_ssymm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *B, const int32_T ldb, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_zsymm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern real32_T cblas_sdsdot_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dgbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cgbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_daxpy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cgemv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ctrmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_chemv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zgbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ssyr2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY, real32_T *A, const int32_T lda);
DLL_EXPORT_CC extern real_T cblas_ddot_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dsyrk_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_cher2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_dger_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY, real_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_chpr_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, void *X, const int32_T incX, void *A);
DLL_EXPORT_CC extern void cblas_srotmg_p4OTtGwLt8ENvzdl38NWBD(real32_T *d1, real32_T *d2, real32_T *b1, const real32_T b2, real32_T *P);
DLL_EXPORT_CC extern void cblas_cher_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, void *X, const int32_T incX, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_cgeru_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_cgerc_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_drot_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, real_T *X, const int32_T incX, real_T *Y, const int32_T incY, const real_T c, const real_T s);
DLL_EXPORT_CC extern void cblas_csyrk_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_ztrsm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_chpmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *Ap, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_csscal_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dtrsm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, real_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_zgeru_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zdscal_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dscal_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T alpha, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsyr2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY, real_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_drotmg_p4OTtGwLt8ENvzdl38NWBD(real_T *d1, real_T *d2, real_T *b1, const real_T b2, real_T *P);
DLL_EXPORT_CC extern void cblas_sgbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ztbsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsyr_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, real_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_cherk_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real32_T alpha, void *A, const int32_T lda, const real32_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_chemm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void gfgphp_p4OTtGwLt8ENvzdl38NWBD(real_T *Q, real_T *R, real_T *Qf, real_T *zmax, real_T *zmin, real_T *z, int32_T T, int32_T n, int32_T m, int32_T nz, real_T *gf, real_T *gp, real_T *hp);
DLL_EXPORT_CC extern real32_T cblas_sdot_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dsymm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, const real_T *B, const int32_T ldb, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_sspr2_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY, real32_T *A);
DLL_EXPORT_CC extern void dnudz_p4OTtGwLt8ENvzdl38NWBD(real_T *A, real_T *B, real_T *At, real_T *Bt, real_T *eyen, real_T *eyem, real_T *Q, real_T *R, real_T *Qf, real_T *hp, real_T *rd, real_T *rp, int32_T T, int32_T n, int32_T m, int32_T nz, real_T kappa, real_T *dnu, real_T *dz);
DLL_EXPORT_CC extern void cblas_cgemm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_dsyr2k_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T *B, const int32_T ldb, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_zgemv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_stbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_strmm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, real32_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_drotg_p4OTtGwLt8ENvzdl38NWBD(real_T *a, real_T *b, real_T *c, real_T *s);
DLL_EXPORT_CC extern void cblas_sswap_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zhemv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zsyr2k_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_zdotc_sub_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotc);
DLL_EXPORT_CC extern void cblas_ssyr_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, real32_T *A, const int32_T lda);
DLL_EXPORT_CC extern void resdresp_p4OTtGwLt8ENvzdl38NWBD(real_T *rd, real_T *rp, int32_T T, int32_T n, int32_T nz, real_T *resd, real_T *resp, real_T *res);
DLL_EXPORT_CC extern void cblas_ctrmm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_csymm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_ztbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_srotg_p4OTtGwLt8ENvzdl38NWBD(real32_T *a, real32_T *b, real32_T *c, real32_T *s);
DLL_EXPORT_CC extern void cblas_sgemm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *B, const int32_T ldb, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_caxpy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dtrsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dspr_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, real_T *Ap);
DLL_EXPORT_CC extern void cblas_dtrmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztrmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctpsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctbsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dtbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztrmm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_strsm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, real32_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_ssyr2k_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *B, const int32_T ldb, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_dtrmm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, real_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_zher2k_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, const real_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_dspmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *Ap, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_stpsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *Ap, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zher_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, void *X, const int32_T incX, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zdotu_sub_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotu);
DLL_EXPORT_CC extern void cblas_sspr_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, real32_T *Ap);
DLL_EXPORT_CC extern void cblas_dswap_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, real_T *X, const int32_T incX, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern real32_T cblas_sasum_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zgemm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_ztpmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_drotm_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, real_T *X, const int32_T incX, real_T *Y, const int32_T incY, const real_T *P);
DLL_EXPORT_CC extern real_T cblas_dasum_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T *X, const int32_T incX);
DLL_EXPORT_CC extern real32_T cblas_scasum_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void rdrp_p4OTtGwLt8ENvzdl38NWBD(real_T *A, real_T *B, real_T *Q, real_T *R, real_T *Qf, real_T *z, real_T *nu, real_T *gf, real_T *gp, real_T *b, int32_T T, int32_T n, int32_T m, int32_T nz, real_T kappa, real_T *rd, real_T *rp, real_T *Ctnu);
DLL_EXPORT_CC extern uint64_T cblas_idamax_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real_T *X, const int32_T incX);
DLL_EXPORT_CC extern uint64_T cblas_isamax_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern real_T cblas_dzasum_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctrsm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_sger_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY, real32_T *A, const int32_T lda);
DLL_EXPORT_CC extern real_T cblas_dsdot_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zcopy_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dtpmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *Ap, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ssbmv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dtpsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *Ap, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_srot_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY, const real32_T c, const real32_T s);
DLL_EXPORT_CC extern void cblas_ctrsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dgemv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dgemm_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T *B, const int32_T ldb, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_stbsv_p4OTtGwLt8ENvzdl38NWBD(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern real32_T cblas_scnrm2_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_srotm_p4OTtGwLt8ENvzdl38NWBD(const int32_T N, real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY, const real32_T *P);

/* Function Definitions */
DLL_EXPORT_CC const uint8_T *get_checksum_source_info(int32_T *size);
#ifdef __cplusplus
}
#endif

