#include "customcode_jMJ9RhTWoOCuqsvNlzAENF.h"
#ifdef __cplusplus
extern "C" {
#endif


/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */
DLL_EXPORT_CC extern const char_T *get_dll_checksum_jMJ9RhTWoOCuqsvNlzAENF(void);
DLL_EXPORT_CC extern void cblas_zgemm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_cher_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, void *X, const int32_T incX, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zdotc_sub_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotc);
DLL_EXPORT_CC extern void cblas_stpsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *Ap, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztrsm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_dcopy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T *X, const int32_T incX, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ssbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cgemm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_srot_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY, const real32_T c, const real32_T s);
DLL_EXPORT_CC extern real_T cblas_dzasum_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dspmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *Ap, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ctrmm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_ztbsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_chbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_drotmg_jMJ9RhTWoOCuqsvNlzAENF(real_T *d1, real_T *d2, real_T *b1, const real_T b2, real_T *P);
DLL_EXPORT_CC extern uint64_T cblas_icamax_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zher2k_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, const real_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_sswap_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_chemm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_csscal_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dtbsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsyrk_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_cher2k_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, const real32_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_csyr2k_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern real_T cblas_dsdot_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ztpsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dgbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dtrmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern real_T cblas_dasum_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zaxpy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dtbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztrmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dspr_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, real_T *Ap);
DLL_EXPORT_CC extern void cblas_zhemv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_caxpy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern real32_T cblas_sasum_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctrmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zsyr2k_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_strsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void mpc_jMJ9RhTWoOCuqsvNlzAENF(int32_T T, int32_T m, int32_T n, int32_T niters, real_T kappa, real_T *A, real_T *B, real_T *Q, real_T *Qf, real_T *R, real_T *xmin, real_T *xmax, real_T *umin, real_T *umax, real_T *X0, real_T *U0, real_T *x0, real_T *U, real_T *X);
DLL_EXPORT_CC extern void cblas_sger_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY, real32_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_chpr2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *Ap);
DLL_EXPORT_CC extern void cblas_drotm_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, real_T *X, const int32_T incX, real_T *Y, const int32_T incY, const real_T *P);
DLL_EXPORT_CC extern void cblas_sgbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dsyr2k_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T *B, const int32_T ldb, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_stbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ztrsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_cherk_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real32_T alpha, void *A, const int32_T lda, const real32_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_zcopy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ztbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zhpr2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *Ap);
DLL_EXPORT_CC extern void cblas_sscal_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T alpha, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_csymm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_cgbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dger_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY, real_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_dtpmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *Ap, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zsyrk_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_dtrmm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, real_T *B, const int32_T ldb);
DLL_EXPORT_CC extern uint64_T cblas_izamax_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern real32_T cblas_snrm2_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ctbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_cdotu_sub_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotu);
DLL_EXPORT_CC extern void cblas_ssyr_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, real32_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_dgemm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T *B, const int32_T ldb, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_zgerc_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zsymm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_dtrsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *A, const int32_T lda, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void rdrp_jMJ9RhTWoOCuqsvNlzAENF(real_T *A, real_T *B, real_T *Q, real_T *R, real_T *Qf, real_T *z, real_T *nu, real_T *gf, real_T *gp, real_T *b, int32_T T, int32_T n, int32_T m, int32_T nz, real_T kappa, real_T *rd, real_T *rp, real_T *Ctnu);
DLL_EXPORT_CC extern void cblas_zgemv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern real_T cblas_dnrm2_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsyr_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, real_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zhbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern real32_T cblas_scasum_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dtrsm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, real_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_ctpsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_strmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_drotg_jMJ9RhTWoOCuqsvNlzAENF(real_T *a, real_T *b, real_T *c, real_T *s);
DLL_EXPORT_CC extern void cblas_ctpmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_sspmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *Ap, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_saxpy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dspr2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY, real_T *A);
DLL_EXPORT_CC extern void cblas_ssyrk_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_dtpsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real_T *Ap, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsymm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, const real_T *B, const int32_T ldb, const real_T beta, real_T *C, const int32_T ldc);
DLL_EXPORT_CC extern real32_T cblas_sdsdot_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ssyr2k_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *B, const int32_T ldb, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_sgemm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_TRANSPOSE TransB, const int32_T M, const int32_T N, const int32_T K, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *B, const int32_T ldb, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_zgeru_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_zhpmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *Ap, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cher2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_ztrmm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_daxpy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_stpmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const real32_T *Ap, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_sgemv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cgerc_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_cgeru_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const int32_T M, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_srotg_jMJ9RhTWoOCuqsvNlzAENF(real32_T *a, real32_T *b, real32_T *c, real32_T *s);
DLL_EXPORT_CC extern void cblas_dscal_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T alpha, real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dsbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const int32_T K, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_srotm_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY, const real32_T *P);
DLL_EXPORT_CC extern real_T cblas_dznrm2_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zdotu_sub_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotu);
DLL_EXPORT_CC extern void cblas_zdscal_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_sspr2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY, real32_T *A);
DLL_EXPORT_CC extern void cblas_zgbmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const int32_T KL, const int32_T KU, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zhpr_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, void *X, const int32_T incX, void *A);
DLL_EXPORT_CC extern void cblas_zher_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, void *X, const int32_T incX, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_dsymv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ctbsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_dgemv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, const real_T alpha, const real_T *A, const int32_T lda, const real_T *X, const int32_T incX, const real_T beta, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void resdresp_jMJ9RhTWoOCuqsvNlzAENF(real_T *rd, real_T *rp, int32_T T, int32_T n, int32_T nz, real_T *resd, real_T *resp, real_T *res);
DLL_EXPORT_CC extern void cblas_strsm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, real32_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_ztpmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *Ap, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zher2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *X, const int32_T incX, void *Y, const int32_T incY, void *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_stbsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, const int32_T K, const real32_T *A, const int32_T lda, real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_cscal_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ssymv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *X, const int32_T incX, const real32_T beta, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zscal_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *alpha, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_zswap_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_srotmg_jMJ9RhTWoOCuqsvNlzAENF(real32_T *d1, real32_T *d2, real32_T *b1, const real32_T b2, real32_T *P);
DLL_EXPORT_CC extern void cblas_drot_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, real_T *X, const int32_T incX, real_T *Y, const int32_T incY, const real_T c, const real_T s);
DLL_EXPORT_CC extern void cblas_cdotc_sub_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY, void *dotc);
DLL_EXPORT_CC extern void cblas_cswap_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_dswap_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, real_T *X, const int32_T incX, real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void fmpcsolve_jMJ9RhTWoOCuqsvNlzAENF(real_T *A, real_T *B, real_T *At, real_T *Bt, real_T *eyen, real_T *eyem, real_T *Q, real_T *R, real_T *Qf, real_T *zmax, real_T *zmin, real_T *x, real_T *z, int32_T T, int32_T n, int32_T m, int32_T nz, int32_T niters, real_T kappa);
DLL_EXPORT_CC extern void dnudz_jMJ9RhTWoOCuqsvNlzAENF(real_T *A, real_T *B, real_T *At, real_T *Bt, real_T *eyen, real_T *eyem, real_T *Q, real_T *R, real_T *Qf, real_T *hp, real_T *rd, real_T *rp, int32_T T, int32_T n, int32_T m, int32_T nz, real_T kappa, real_T *dnu, real_T *dz);
DLL_EXPORT_CC extern uint64_T cblas_isamax_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T *X, const int32_T incX);
DLL_EXPORT_CC extern real32_T cblas_scnrm2_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX);
DLL_EXPORT_CC extern real32_T cblas_sdot_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_cgemv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_TRANSPOSE TransA, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zhemm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern real_T cblas_ddot_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_chemv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *A, const int32_T lda, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_zherk_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, const real_T alpha, void *A, const int32_T lda, const real_T beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_scopy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real32_T *X, const int32_T incX, real32_T *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ccopy_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, void *X, const int32_T incX, void *Y, const int32_T incY);
DLL_EXPORT_CC extern uint64_T cblas_idamax_jMJ9RhTWoOCuqsvNlzAENF(const int32_T N, const real_T *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_chpr_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, void *X, const int32_T incX, void *A);
DLL_EXPORT_CC extern void cblas_dsyr2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real_T alpha, const real_T *X, const int32_T incX, const real_T *Y, const int32_T incY, real_T *A, const int32_T lda);
DLL_EXPORT_CC extern void cblas_ctrsv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T N, void *A, const int32_T lda, void *X, const int32_T incX);
DLL_EXPORT_CC extern void cblas_ssymm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, const real32_T *B, const int32_T ldb, const real32_T beta, real32_T *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_sspr_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, real32_T *Ap);
DLL_EXPORT_CC extern void gfgphp_jMJ9RhTWoOCuqsvNlzAENF(real_T *Q, real_T *R, real_T *Qf, real_T *zmax, real_T *zmin, real_T *z, int32_T T, int32_T n, int32_T m, int32_T nz, real_T *gf, real_T *gp, real_T *hp);
DLL_EXPORT_CC extern void cblas_chpmv_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, void *alpha, void *Ap, void *X, const int32_T incX, void *beta, void *Y, const int32_T incY);
DLL_EXPORT_CC extern void cblas_ctrsm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, void *alpha, void *A, const int32_T lda, void *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_csyrk_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE Trans, const int32_T N, const int32_T K, void *alpha, void *A, const int32_T lda, void *beta, void *C, const int32_T ldc);
DLL_EXPORT_CC extern void cblas_strmm_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER Order, const enum CBLAS_SIDE Side, const enum CBLAS_UPLO Uplo, const enum CBLAS_TRANSPOSE TransA, const enum CBLAS_DIAG Diag, const int32_T M, const int32_T N, const real32_T alpha, const real32_T *A, const int32_T lda, real32_T *B, const int32_T ldb);
DLL_EXPORT_CC extern void cblas_ssyr2_jMJ9RhTWoOCuqsvNlzAENF(const enum CBLAS_ORDER order, const enum CBLAS_UPLO Uplo, const int32_T N, const real32_T alpha, const real32_T *X, const int32_T incX, const real32_T *Y, const int32_T incY, real32_T *A, const int32_T lda);

/* Function Definitions */
DLL_EXPORT_CC const uint8_T *get_checksum_source_info(int32_T *size);
#ifdef __cplusplus
}
#endif

