#include "customcode_oU1T82aSzt3vnGSxPPILQH.h"
#ifdef __cplusplus
extern "C" {
#endif


/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */
DLL_EXPORT_CC extern const char_T *get_dll_checksum_oU1T82aSzt3vnGSxPPILQH(void);
DLL_EXPORT_CC extern void cblas_chpr2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__Ap);
DLL_EXPORT_CC extern void cblas_sswap_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, real32_T *__X, const int32_T __incX, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern real_T cblas_dasum_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dsbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const int32_T __K, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__X, const int32_T __incX, const real_T __beta, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_cdotu_sub_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__dotu);
DLL_EXPORT_CC extern void catlas_zaxpby_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dtrsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real_T *__A, const int32_T __lda, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zgerc_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const int32_T __M, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_chpmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__Ap, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_zhemm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void mpc_oU1T82aSzt3vnGSxPPILQH(int32_T T, int32_T m, int32_T n, int32_T niters, real_T kappa, real_T *A, real_T *B, real_T *Q, real_T *Qf, real_T *R, real_T *xmin, real_T *xmax, real_T *umin, real_T *umax, real_T *X0, real_T *U0, real_T *x0, real_T *U, real_T *X);
DLL_EXPORT_CC extern void cblas_zgemv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_stpsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real32_T *__Ap, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_cdotc_sub_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__dotc);
DLL_EXPORT_CC extern real32_T cblas_snrm2_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ccopy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern real_T cblas_ddot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T *__X, const int32_T __incX, const real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern real_T cblas_dsdot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T *__X, const int32_T __incX, const real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern real32_T cblas_sdot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T *__X, const int32_T __incX, const real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_zher2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern int32_T cblas_icamax_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dtpmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real_T *__Ap, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_caxpy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dtbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, const real_T *__A, const int32_T __lda, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_srotm_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, real32_T *__X, const int32_T __incX, real32_T *__Y, const int32_T __incY, const real32_T *__P);
DLL_EXPORT_CC extern void cblas_dgbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, const int32_T __KL, const int32_T __KU, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__X, const int32_T __incX, const real_T __beta, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_ztrsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zdotu_sub_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__dotu);
DLL_EXPORT_CC extern void cblas_sgbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, const int32_T __KL, const int32_T __KU, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__X, const int32_T __incX, const real32_T __beta, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_ctrsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_drot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, real_T *__X, const int32_T __incX, real_T *__Y, const int32_T __incY, const real_T __c, const real_T __s);
DLL_EXPORT_CC extern void cblas_ztrmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_drotg_oU1T82aSzt3vnGSxPPILQH(real_T *__a, real_T *__b, real_T *__c, real_T *__s);
DLL_EXPORT_CC extern void cblas_dscal_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T __alpha, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_cscal_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ztpmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__Ap, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ztbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dtbsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, const real_T *__A, const int32_T __lda, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ctbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zhpmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__Ap, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_drotmg_oU1T82aSzt3vnGSxPPILQH(real_T *__d1, real_T *__d2, real_T *__b1, const real_T __b2, real_T *__P);
DLL_EXPORT_CC extern real_T cblas_dznrm2_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_stpmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real32_T *__Ap, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dsyr_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, real_T *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_zdrot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, const real_T __c, const real_T __s);
DLL_EXPORT_CC extern void rdrp_oU1T82aSzt3vnGSxPPILQH(real_T *A, real_T *B, real_T *Q, real_T *R, real_T *Qf, real_T *z, real_T *nu, real_T *gf, real_T *gp, real_T *b, int32_T T, int32_T n, int32_T m, int32_T nz, real_T kappa, real_T *rd, real_T *rp, real_T *Ctnu);
DLL_EXPORT_CC extern void cblas_strsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real32_T *__A, const int32_T __lda, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zrotg_oU1T82aSzt3vnGSxPPILQH(void *__a, void *__b, void *__c, void *__s);
DLL_EXPORT_CC extern void cblas_zdscal_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T __alpha, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_chemm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_srot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, real32_T *__X, const int32_T __incX, real32_T *__Y, const int32_T __incY, const real32_T __c, const real32_T __s);
DLL_EXPORT_CC extern void cblas_zscal_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ctrmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_stbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, const real32_T *__A, const int32_T __lda, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_cswap_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern int32_T cblas_idamax_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ztrsm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_sscal_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T __alpha, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_sgemv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__X, const int32_T __incX, const real32_T __beta, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_crotg_oU1T82aSzt3vnGSxPPILQH(void *__a, void *__b, void *__c, void *__s);
DLL_EXPORT_CC extern void cblas_stbsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, const real32_T *__A, const int32_T __lda, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_csrot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, const real32_T __c, const real32_T __s);
DLL_EXPORT_CC extern void cblas_drotm_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, real_T *__X, const int32_T __incX, real_T *__Y, const int32_T __incY, const real_T *__P);
DLL_EXPORT_CC extern real_T cblas_dzasum_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void appleblas_dgeadd_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __order, const enum CBLAS_TRANSPOSE __transA, const enum CBLAS_TRANSPOSE __transB, const int32_T __m, const int32_T __n, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T __beta, const real_T *__B, const int32_T __ldb, real_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void catlas_dset_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T __alpha, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ztbsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_cgemv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dswap_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, real_T *__X, const int32_T __incX, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void fmpcsolve_oU1T82aSzt3vnGSxPPILQH(real_T *A, real_T *B, real_T *At, real_T *Bt, real_T *eyen, real_T *eyem, real_T *Q, real_T *R, real_T *Qf, real_T *zmax, real_T *zmin, real_T *x, real_T *z, int32_T T, int32_T n, int32_T m, int32_T nz, int32_T niters, real_T kappa);
DLL_EXPORT_CC extern real_T cblas_dnrm2_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void resdresp_oU1T82aSzt3vnGSxPPILQH(real_T *rd, real_T *rp, int32_T T, int32_T n, int32_T nz, real_T *resd, real_T *resp, real_T *res);
DLL_EXPORT_CC extern void cblas_saxpy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dsyrk_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T __beta, real_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern real32_T cblas_scnrm2_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern int32_T cblas_isamax_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dtrsm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, const real_T __alpha, const real_T *__A, const int32_T __lda, real_T *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_dsyr2k_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__B, const int32_T __ldb, const real_T __beta, real_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void catlas_saxpby_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, const real32_T __beta, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_chpr_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, void *__X, const int32_T __incX, void *__A);
DLL_EXPORT_CC extern void cblas_zcopy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dgemv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__X, const int32_T __incX, const real_T __beta, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dtpsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real_T *__Ap, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zgeru_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const int32_T __M, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_sger_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const int32_T __M, const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, const real32_T *__Y, const int32_T __incY, real32_T *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_daxpy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void SetBLASParamErrorProc_oU1T82aSzt3vnGSxPPILQH(BLASParamErrorProc __ErrorProc);
DLL_EXPORT_CC extern void cblas_zgemm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_TRANSPOSE __TransB, const int32_T __M, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void catlas_zset_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_strmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real32_T *__A, const int32_T __lda, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_cgbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, const int32_T __KL, const int32_T __KU, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void catlas_daxpby_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, const real_T __beta, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern real32_T cblas_scasum_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ctbsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const int32_T __K, void *__A, const int32_T __lda, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zaxpy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern real32_T cblas_sasum_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_srotg_oU1T82aSzt3vnGSxPPILQH(real32_T *__a, real32_T *__b, real32_T *__c, real32_T *__s);
DLL_EXPORT_CC extern void cblas_ssbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const int32_T __K, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__X, const int32_T __incX, const real32_T __beta, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_zswap_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void catlas_caxpby_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_csscal_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T __alpha, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void catlas_cset_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__alpha, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dcopy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real_T *__X, const int32_T __incX, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_zsyr2k_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_srotmg_oU1T82aSzt3vnGSxPPILQH(real32_T *__d1, real32_T *__d2, real32_T *__b1, const real32_T __b2, real32_T *__P);
DLL_EXPORT_CC extern void cblas_csyrk_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void dnudz_oU1T82aSzt3vnGSxPPILQH(real_T *A, real_T *B, real_T *At, real_T *Bt, real_T *eyen, real_T *eyem, real_T *Q, real_T *R, real_T *Qf, real_T *hp, real_T *rd, real_T *rp, int32_T T, int32_T n, int32_T m, int32_T nz, real_T kappa, real_T *dnu, real_T *dz);
DLL_EXPORT_CC extern int32_T cblas_izamax_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ctpmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__Ap, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_dtrmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, const real_T *__A, const int32_T __lda, real_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern void gfgphp_oU1T82aSzt3vnGSxPPILQH(real_T *Q, real_T *R, real_T *Qf, real_T *zmax, real_T *zmin, real_T *z, int32_T T, int32_T n, int32_T m, int32_T nz, real_T *gf, real_T *gp, real_T *hp);
DLL_EXPORT_CC extern void cblas_cher2k_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, const real32_T __beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void catlas_sset_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T __alpha, real32_T *__X, const int32_T __incX);
DLL_EXPORT_CC extern real32_T cblas_sdsdot_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, const real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_zdotc_sub_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__dotc);
DLL_EXPORT_CC extern void cblas_strsm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, const real32_T __alpha, const real32_T *__A, const int32_T __lda, real32_T *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_dtrmm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, const real_T __alpha, const real_T *__A, const int32_T __lda, real_T *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_zher_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, void *__X, const int32_T __incX, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_sgemm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_TRANSPOSE __TransB, const int32_T __M, const int32_T __N, const int32_T __K, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__B, const int32_T __ldb, const real32_T __beta, real32_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_ssyr_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, real32_T *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_ssymm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const int32_T __M, const int32_T __N, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__B, const int32_T __ldb, const real32_T __beta, real32_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_dspr2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, const real_T *__Y, const int32_T __incY, real_T *__A);
DLL_EXPORT_CC extern void cblas_zhpr2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__Ap);
DLL_EXPORT_CC extern void cblas_ssyr2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, const real32_T *__Y, const int32_T __incY, real32_T *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_scopy_oU1T82aSzt3vnGSxPPILQH(const int32_T __N, const real32_T *__X, const int32_T __incX, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void appleblas_sgeadd_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __order, const enum CBLAS_TRANSPOSE __transA, const enum CBLAS_TRANSPOSE __transB, const int32_T __m, const int32_T __n, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T __beta, const real32_T *__B, const int32_T __ldb, real32_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_ssyrk_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T __beta, real32_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_dsymv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__X, const int32_T __incX, const real_T __beta, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_ztrmm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_cher2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_dspr_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, real_T *__Ap);
DLL_EXPORT_CC extern void cblas_dsyr2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, const real_T *__Y, const int32_T __incY, real_T *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_zsymm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_csymm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_dger_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const int32_T __M, const int32_T __N, const real_T __alpha, const real_T *__X, const int32_T __incX, const real_T *__Y, const int32_T __incY, real_T *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_chbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_cher_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, void *__X, const int32_T __incX, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_zherk_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, const real_T __alpha, void *__A, const int32_T __lda, const real_T __beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_chemv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_ctrmm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_dspmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, const real_T *__Ap, const real_T *__X, const int32_T __incX, const real_T __beta, real_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_strmm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, const real32_T __alpha, const real32_T *__A, const int32_T __lda, real32_T *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_zsyrk_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_ztpsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__Ap, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_ssyr2k_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__B, const int32_T __ldb, const real32_T __beta, real32_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_ssymv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, const real32_T *__A, const int32_T __lda, const real32_T *__X, const int32_T __incX, const real32_T __beta, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_dsymm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const int32_T __M, const int32_T __N, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__B, const int32_T __ldb, const real_T __beta, real_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_ctpsv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __N, void *__Ap, void *__X, const int32_T __incX);
DLL_EXPORT_CC extern void cblas_zher2k_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, const real_T __beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_cgeru_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const int32_T __M, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_sspr_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, real32_T *__Ap);
DLL_EXPORT_CC extern void cblas_dgemm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_TRANSPOSE __TransB, const int32_T __M, const int32_T __N, const int32_T __K, const real_T __alpha, const real_T *__A, const int32_T __lda, const real_T *__B, const int32_T __ldb, const real_T __beta, real_T *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_zgbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const int32_T __M, const int32_T __N, const int32_T __KL, const int32_T __KU, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_zhemv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_ctrsm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_SIDE __Side, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_DIAG __Diag, const int32_T __M, const int32_T __N, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb);
DLL_EXPORT_CC extern void cblas_cgerc_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const int32_T __M, const int32_T __N, void *__alpha, void *__X, const int32_T __incX, void *__Y, const int32_T __incY, void *__A, const int32_T __lda);
DLL_EXPORT_CC extern void cblas_cherk_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, const real32_T __alpha, void *__A, const int32_T __lda, const real32_T __beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_zhbmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__X, const int32_T __incX, void *__beta, void *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_sspr2_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, const real32_T *__X, const int32_T __incX, const real32_T *__Y, const int32_T __incY, real32_T *__A);
DLL_EXPORT_CC extern void cblas_cgemm_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_TRANSPOSE __TransA, const enum CBLAS_TRANSPOSE __TransB, const int32_T __M, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);
DLL_EXPORT_CC extern void cblas_zhpr_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real_T __alpha, void *__X, const int32_T __incX, void *__A);
DLL_EXPORT_CC extern void cblas_sspmv_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const int32_T __N, const real32_T __alpha, const real32_T *__Ap, const real32_T *__X, const int32_T __incX, const real32_T __beta, real32_T *__Y, const int32_T __incY);
DLL_EXPORT_CC extern void cblas_csyr2k_oU1T82aSzt3vnGSxPPILQH(const enum CBLAS_ORDER __Order, const enum CBLAS_UPLO __Uplo, const enum CBLAS_TRANSPOSE __Trans, const int32_T __N, const int32_T __K, void *__alpha, void *__A, const int32_T __lda, void *__B, const int32_T __ldb, void *__beta, void *__C, const int32_T __ldc);

/* Function Definitions */
DLL_EXPORT_CC const uint8_T *get_checksum_source_info(int32_T *size);
#ifdef __cplusplus
}
#endif

